//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2Topicos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int CustomerID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> TerritoryID { get; set; }
        public string AccountNumber { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string PersonType { get; set; }
        public Nullable<bool> NameStyle { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public Nullable<int> EmailPromotion { get; set; }
        public Nullable<int> AddressID { get; set; }
    }
}
